# Generated by Django 5.2.1 on 2025-05-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='苹果ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='谷歌ID'),
        ),
    ]
